# Generated by Django 6.0.4 on 2026-05-07 15:14

import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.PositiveIntegerField(default=1, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('report_party_file', filebrowser.fields.FileBrowseField(default='settings.MEDIA_ROOT/sample.csv', max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
