# Generated by Django 6.0.4 on 2026-05-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='report_party_file',
            new_name='report_party',
        ),
    ]
