# Generated by Django 6.0.4 on 2026-04-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_number',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='updated',
        ),
        migrations.AddField(
            model_name='party',
            name='platform_number',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
