# Generated by Django 6.0.4 on 2026-05-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_rename_report_party_file_party_report_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='report_party',
            new_name='report_party_file',
        ),
    ]
