# Generated by Django 6.0.4 on 2026-05-07 16:25

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_rename_report_party_party_report_party_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='report_party_file',
            field=filebrowser.fields.FileBrowseField(default='text.csv', max_length=250, null=True),
        ),
    ]
