# Generated by Django 6.0.4 on 2026-05-14 16:36

import filebrowser.fields
import parties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_party_report_party_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterField(
            model_name='party',
            name='platform_number',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='номер линии'),
        ),
        migrations.AlterField(
            model_name='party',
            name='report_party_file',
            field=filebrowser.fields.FileBrowseField(default=parties.models.Party.def_file_name, max_length=250, null=True, verbose_name='отчет по партии'),
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
    ]
